### ISSUE TITLE
Alternative API for Overwatch

### ISSUE THREAD

**Issue by PyroclasticMayhem** [perhion/aru#10]
LootBoxAPI, the current API being used to get information from an OW profile no longer works. An alternative is needed, the closest one I have found is Ow-API https://ow-api.com/. 

See /commands/overwatch.js	for existing code and update to use Ow-API.

**Comment by DennyScott** [comment]
I can take this on for you!

**Comment by PyroclasticMayhem** [comment]
Thanks @DennyScott.
