### ISSUE TITLE
Alternative API for Movies

### ISSUE THREAD

**Issue by PyroclasticMayhem** [perhion/aru#12]
OMDbAPI which is used for the command at /commands/imdb.js has gone private. One replacement that I have found is The Movie DB at https://www.themoviedb.org/documentation/api.

An option is renaming imdb.js and update the fields to use the new API. API keys can be added to config.json.

**Comment by brookesargent** [comment]
Is anyone working on this yet? If not, I'd love to give it a try!

**Comment by PyroclasticMayhem** [comment]
Go ahead @brookesargent

**Comment by PyroclasticMayhem** [comment]
Resolved in commit 58688c117204f6095a629bf4dd47a1f1dde30428.
