### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by ETLegacyy** [perhion/aru#31]
No one probably noticed this, but, when you make the bot move to another channel, the bot will probably break.

**Comment by ETLegacyy** [comment]
To reproduce this follow this:

1. Connect the bot to vc, move the bot to a vc."
2. Disconnect the bot.
3. When you disconnect it, try playing a song.

What you should expect:
It won't connect to the VC you are in.

To fix:
Restart the bot.

But, it's better if you fix it.

**Comment by PyroclasticMayhem** [comment]
I'm attempting to follow your steps to reproduce the bug. Could you specify what you mean by disconnect the bot?

**Comment by ETLegacyy** [comment]
Disconnect the bot from voice channel.

**Comment by ETLegacyy** [comment]
@PyroclasticMayhem i'm a developer as well, i can try to contribute to somethings if you want :)
