### ISSUE TITLE
Use JS Standard Style

### ISSUE THREAD

**Issue by PyroclasticMayhem** [perhion/aru#7]
Use [JS Standard](https://github.com/standard/standard) to maintain a consistent coding convention with clear guidelines.

Code that are in the `legacy_commands` folder need to be converted and moved over to the `commands` folder.

### Code to convert

- [x] about
- [x] chatbot
- [x] anime
- [x] ping
- [x] help
- [ ] imdb
- [ ] manga
- [ ] meme
- [ ] overwatch
- [ ] profiler

**Comment by arojunior** [comment]
Can I take this one?

**Comment by PyroclasticMayhem** [comment]
Sure!

**Comment by arojunior** [comment]
Ok, working on it.

**Comment by theRoughCode** [comment]
Finished rest of code conversion!

**Comment by kytwb** [comment]
@theRoughCode leave priority to @arojunior who claimed this one.

**Comment by PyroclasticMayhem** [comment]
Thank you @arojunior!
